# This file contains all the constants that are used in this project

ACCESS_GRANTED = "GRANTED"
ACCESS_DENIED = "DENIED"

REASON_AUTHORIZED = "Credential authorized"
REASON_NOT_FOUND = "Credential not found"
REASON_REVOKED = "Credential revoked"

BLE_RESPONSE_PONG = "PONG"
BLE_RESPONSE_UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
BLE_RESPONSE_INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
BLE_RESPONSE_NO_LOGS = "NO_LOGS"
BLE_RESPONSE_NO_CREDENTIALS = "NO_CREDENTIALS"
BLE_RESPONSE_CREDENTIAL_NOT_FOUND = "CREDENTIAL_NOT_FOUND"
BLE_RESPONSE_ENROLL_MODE_ON = "ENROLL_MODE_ON"
BLE_RESPONSE_ENROLL_MODE_OFF = "ENROLL_MODE_OFF"
BLE_RESPONSE_ENROLL_SERVICE_NOT_AVAILABLE = "ENROLL_SERVICE_NOT_AVAILABLE"
BLE_RESPONSE_NONE = "NONE"